# Módulo 04 — Búsqueda semántica

## Objetivo

Este módulo convierte una consulta escrita por una persona en un embedding y utiliza el índice del Módulo 03 para recuperar documentos semánticamente relacionados. La consulta puede estar en English, Español o Português.

## Flujo de una búsqueda

```text
query
  ↓
embedding de la consulta, con la misma configuración del corpus
  ↓
vecinos más cercanos en el índice
  ↓
distancia coseno
  ↓
similitud = 1 - distancia
  ↓
documentos relacionados ordenados
```

## Entradas

Se cargan `models/documents.json`, `models/semantic_index.joblib` y la configuración del modelo. Los embeddings de documentos no se recalculan: el índice ya conserva la matriz utilizada en el Módulo 03.

## Salida

`search_related(query, limit=3)` devuelve como máximo tres resultados con `id`, `titulo`, `idioma` y `similitud`. La posición devuelta por el índice se utiliza para recuperar los metadatos correctos.

## Decisiones y limitaciones

La consulta debe codificarse con el mismo modelo y normalización que los documentos. Una similitud alta indica cercanía en el espacio aprendido, pero no garantiza que dos textos sean idénticos ni que la respuesta sea factual. El índice brute-force puede requerir optimización cuando crezca el corpus.

## Ejemplos

Se prueban consultas equivalentes en inglés, español y portugués para observar cómo el modelo multilingüe recupera documentos relacionados sin utilizar categorías inventadas.

In [1]:
import sys
from pathlib import Path
import joblib
sys.path.insert(0, str(Path.cwd() / 'src'))
from techmind.config import get_paths, MODEL_NAME
from techmind.persistence.artifacts import load_documents
from techmind.search.semantic_search import search_related
paths = get_paths(); documents = load_documents(paths.documents); index = joblib.load(paths.index)
for query in ['Artificial intelligence impact', 'Impacto de la inteligencia artificial', 'Impacto da inteligência artificial']:
    display(search_related(query, limit=3, index=index, documents=documents, model_name=MODEL_NAME))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

,id,titulo,idioma,similitud
0,es/philosophy-of-learning90,Cuenta regresiva de la inteligencia - La Degen...,es,0.561612
1,pt/philosophy-of-learning90,Contagem Regressiva da Inteligência - A Degene...,pt,0.560803
2,pt/alternative-commentary44,Qual philosophy-of-learning nos aguarda no fim...,pt,0.505635

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

,id,titulo,idioma,similitud
0,pt/philosophy-of-learning90,Contagem Regressiva da Inteligência - A Degene...,pt,0.611831
1,es/philosophy-of-learning90,Cuenta regresiva de la inteligencia - La Degen...,es,0.608777
2,pt/alternative-commentary44,Qual philosophy-of-learning nos aguarda no fim...,pt,0.571213

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

,id,titulo,idioma,similitud
0,pt/philosophy-of-learning90,Contagem Regressiva da Inteligência - A Degene...,pt,0.603070
1,es/philosophy-of-learning90,Cuenta regresiva de la inteligencia - La Degen...,es,0.599430
2,pt/alternative-commentary44,Qual philosophy-of-learning nos aguarda no fim...,pt,0.571467